"""Seeder: Projects and Tasks for Chemical.

A resin scale-up, a reactor turnaround and an export registration programme.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Process Scale-up Protocol" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "Specialty Resin Scale-up - RX-400",
        "project_type": "Process Scale-up",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "Scale-up of the RX-400 epoxy grade from 50 L pilot to the 5 KL reactor.",
        "phases": [
            {
                "subject": "Laboratory Development",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Bench Scale Trial",
                        "type": "Lab Trial",
                        "start": 0,
                        "duration": 10,
                        "designation": "Quality Analyst",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Reaction Kinetics Study",
                        "type": "Lab Trial",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Bench Scale Trial"],
                        "designation": "Quality Analyst",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "HAZOP Review",
                        "type": "Safety",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Reaction Kinetics Study"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Engineering & Procurement",
                "designation": "Production Supervisor",
                "tasks": [
                    {
                        "subject": "Mass Balance & P&ID",
                        "type": "Process Design",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["HAZOP Review"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Reactor Jacket Sizing",
                        "type": "Process Design",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["HAZOP Review"],
                        "designation": "Maintenance Technician",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Continuous Reactor Package",
                        "type": "Procurement",
                        "start": 70,
                        "duration": 20,
                        "designation": "Production Manager",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Shelved in favour of reusing the existing batch "
                        "reactor train.",
                    },
                    {
                        "subject": "Agitator Procurement",
                        "type": "Procurement",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Mass Balance & P&ID"],
                        "designation": "Maintenance Technician",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Plant Trials",
                "designation": "Shift Supervisor",
                "tasks": [
                    {
                        "subject": "Reactor Modification",
                        "type": "Installation",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["HAZOP Review"],
                        "designation": "Maintenance Technician",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Pre-trial Safety Audit",
                        "type": "Safety",
                        "start": 130,
                        "duration": 8,
                        "designation": "Production Supervisor",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "First Plant Trial Batch",
                        "type": "Validation",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Reactor Modification", "Agitator Procurement"],
                        "designation": "Shift Supervisor",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Effluent Load Check",
                        "type": "Validation",
                        "start": 150,
                        "duration": 10,
                        "designation": "Quality Analyst",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Yield Optimisation Runs",
                        "type": "Validation",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["First Plant Trial Batch"],
                        "designation": "Process Operator",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Validation & Release",
                "designation": "Quality Analyst",
                "tasks": [
                    {
                        "subject": "Process Validation Batches",
                        "type": "Validation",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Yield Optimisation Runs"],
                        "designation": "Quality Analyst",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Stability Study",
                        "type": "Validation",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Process Validation Batches"],
                        "designation": "Quality Analyst",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "SOP & Batch Record Release",
                        "type": "Documentation",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Stability Study"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Reactor-3 Turnaround",
        "project_type": "Plant Turnaround",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "Planned 30-day shutdown of the Reactor-3 train for overhaul and re-lining.",
        "phases": [
            {
                "subject": "Preparation",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Scope Freeze",
                        "type": "Process Design",
                        "start": 0,
                        "duration": 12,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Spares Readiness Review",
                        "type": "Procurement",
                        "start": 5,
                        "duration": 10,
                        "designation": "Maintenance Technician",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Isolation & Overhaul",
                "designation": "Maintenance Technician",
                "tasks": [
                    {
                        "subject": "Line Flushing & Isolation",
                        "type": "Installation",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Spares Readiness Review", "Scope Freeze"],
                        "designation": "Plant Operator",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Confined Space Safety Audit",
                        "type": "Safety",
                        "start": 60,
                        "duration": 6,
                        "designation": "Production Supervisor",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Vessel Internal Inspection",
                        "type": "Validation",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Line Flushing & Isolation"],
                        "designation": "Quality Analyst",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Glass Lining Repair",
                        "type": "Installation",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Vessel Internal Inspection"],
                        "designation": "Maintenance Technician",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Restart",
                "designation": "Shift Supervisor",
                "tasks": [
                    {
                        "subject": "Gasket & Valve Replacement",
                        "type": "Installation",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Glass Lining Repair"],
                        "designation": "Maintenance Technician",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Hydro Testing",
                        "type": "Validation",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Glass Lining Repair"],
                        "designation": "Maintenance Technician",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Restart & Stabilisation",
                        "type": "Validation",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Gasket & Valve Replacement", "Hydro Testing"],
                        "designation": "Shift Supervisor",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "REACH Registration - Export Grades",
        "project_type": "Regulatory Programme",
        "priority": "High",
        "start_offset_days": -45,
        "notes": "EU REACH dossier for the three highest-volume export grades.",
        "phases": [
            {
                "subject": "Data Assembly",
                "designation": "Quality Analyst",
                "tasks": [
                    {
                        "subject": "Substance Identity Profile",
                        "type": "Regulatory",
                        "start": 0,
                        "duration": 10,
                        "designation": "Quality Analyst",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Existing Data Gap Analysis",
                        "type": "Regulatory",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Substance Identity Profile"],
                        "designation": "Quality Analyst",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Only Representative Appointment",
                        "type": "Regulatory",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Existing Data Gap Analysis"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Testing",
                "designation": "Quality Analyst",
                "tasks": [
                    {
                        "subject": "Physico-chemical Testing",
                        "type": "Lab Trial",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Existing Data Gap Analysis"],
                        "designation": "Quality Analyst",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Ecotoxicity Testing",
                        "type": "Lab Trial",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Existing Data Gap Analysis"],
                        "designation": "Quality Analyst",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Filing",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Chemical Safety Report",
                        "type": "Documentation",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Only Representative Appointment"],
                        "designation": "Quality Analyst",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Dossier Compilation",
                        "type": "Documentation",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Chemical Safety Report", "Physico-chemical Testing"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "ECHA Submission",
                        "type": "Regulatory",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Dossier Compilation"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Pilot Batch Qualification - Additive AD-9",
        "project_type": "Process Scale-up",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Process Scale-up Protocol",
        "notes": "Kicked off from the standard scale-up protocol.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Chemical Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
