"""Seeder: Projects and Tasks for Solar.

A utility-scale farm, a factory rooftop and an annual O&M contract.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Rooftop Solar Installation" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "2 MW Ground-Mount Farm - Jodhpur",
        "project_type": "Ground-Mount Farm",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "A 2 MWp ground-mounted plant on 9 acres with a 33kV interconnection.",
        "phases": [
            {
                "subject": "Engineering & Approvals",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Topographic Survey",
                        "type": "Survey",
                        "start": 0,
                        "duration": 10,
                        "designation": "Installation Supervisor",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Plant Layout & String Design",
                        "type": "Design",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Topographic Survey"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "DISCOM Connectivity Approval",
                        "type": "Approval",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Plant Layout & String Design"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Procurement",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Module Purchase Order",
                        "type": "Procurement",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["DISCOM Connectivity Approval"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Inverter Purchase Order",
                        "type": "Procurement",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["DISCOM Connectivity Approval"],
                        "designation": "Inverter Technician",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Single-Axis Tracker Package",
                        "type": "Procurement",
                        "start": 70,
                        "duration": 20,
                        "designation": "Production Manager",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Dropped after the yield gain failed to cover the "
                        "tracker capex.",
                    },
                    {
                        "subject": "Cable & BOS Supply",
                        "type": "Procurement",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Module Purchase Order"],
                        "designation": "Cable Technician",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Construction",
                "designation": "Installation Supervisor",
                "tasks": [
                    {
                        "subject": "Pile Foundation Works",
                        "type": "Civil Works",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["DISCOM Connectivity Approval"],
                        "designation": "Installation Supervisor",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Site Safety Audit",
                        "type": "Safety",
                        "start": 130,
                        "duration": 8,
                        "designation": "Site Safety Officer",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Mounting Structure Erection",
                        "type": "Installation",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Pile Foundation Works", "Cable & BOS Supply"],
                        "designation": "Panel Assembly Technician",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Fencing & Site Levelling",
                        "type": "Civil Works",
                        "start": 150,
                        "duration": 10,
                        "designation": "Installation Supervisor",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Module Mounting & Stringing",
                        "type": "Installation",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Mounting Structure Erection"],
                        "designation": "Panel Assembly Technician",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Commissioning",
                "designation": "Commissioning Engineer",
                "tasks": [
                    {
                        "subject": "Inverter & Transformer Fitment",
                        "type": "Installation",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Module Mounting & Stringing"],
                        "designation": "Inverter Technician",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Grid Synchronisation",
                        "type": "Commissioning",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Inverter & Transformer Fitment"],
                        "designation": "Commissioning Engineer",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Plant Handover",
                        "type": "Handover",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Grid Synchronisation"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "500 kW Factory Rooftop - Chakan",
        "project_type": "Rooftop Install",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "A 500 kWp rooftop system on a metal-sheet factory roof under net metering.",
        "phases": [
            {
                "subject": "Assessment",
                "designation": "Installation Supervisor",
                "tasks": [
                    {
                        "subject": "Roof Structural Assessment",
                        "type": "Survey",
                        "start": 0,
                        "duration": 12,
                        "designation": "Installation Supervisor",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Shadow Analysis",
                        "type": "Survey",
                        "start": 5,
                        "duration": 10,
                        "designation": "Installation Supervisor",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Installation",
                "designation": "Installation Supervisor",
                "tasks": [
                    {
                        "subject": "Mounting Structure Erection",
                        "type": "Installation",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Shadow Analysis", "Roof Structural Assessment"],
                        "designation": "Panel Assembly Technician",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Working at Height Safety Audit",
                        "type": "Safety",
                        "start": 60,
                        "duration": 6,
                        "designation": "Site Safety Officer",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Module Mounting",
                        "type": "Installation",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Mounting Structure Erection"],
                        "designation": "Panel Assembly Technician",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "DC Cabling & Combiner Boxes",
                        "type": "Installation",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Module Mounting"],
                        "designation": "Cable Technician",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Handover",
                "designation": "Commissioning Engineer",
                "tasks": [
                    {
                        "subject": "Inverter Installation",
                        "type": "Installation",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["DC Cabling & Combiner Boxes"],
                        "designation": "Inverter Technician",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Performance Ratio Testing",
                        "type": "Commissioning",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["DC Cabling & Combiner Boxes"],
                        "designation": "Commissioning Engineer",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Net Metering Handover",
                        "type": "Handover",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Inverter Installation", "Performance Ratio Testing"],
                        "designation": "Commissioning Engineer",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Annual O&M Contract - Western Cluster",
        "project_type": "O&M Contract",
        "priority": "Medium",
        "start_offset_days": -45,
        "notes": "Annual operations and maintenance across 14 rooftop sites in the western "
        "cluster.",
        "phases": [
            {
                "subject": "Mobilisation",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Site Inventory & Baseline",
                        "type": "Survey",
                        "start": 0,
                        "duration": 10,
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Service Level Agreement",
                        "type": "Handover",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Site Inventory & Baseline"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Client Contract Sign-off",
                        "type": "Approval",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Service Level Agreement"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Baseline",
                "designation": "QC Inspector",
                "tasks": [
                    {
                        "subject": "Spares Kit Stocking",
                        "type": "Procurement",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Service Level Agreement"],
                        "designation": "Cable Technician",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Monitoring Portal Setup",
                        "type": "Commissioning",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Service Level Agreement"],
                        "designation": "Commissioning Engineer",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Service Cycles",
                "designation": "Installation Supervisor",
                "tasks": [
                    {
                        "subject": "Quarterly Cleaning Cycle",
                        "type": "Installation",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Client Contract Sign-off"],
                        "designation": "Panel Assembly Technician",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Thermography Inspection",
                        "type": "Commissioning",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Quarterly Cleaning Cycle", "Spares Kit Stocking"],
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Annual Performance Report",
                        "type": "Handover",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Thermography Inspection"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Residential Rooftop Cluster - Kothrud",
        "project_type": "Rooftop Install",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Rooftop Solar Installation",
        "notes": "A 22-home cluster, opened from the rooftop installation template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Solar Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
