"""Seeder: Projects and Tasks for Electrical.

A switchgear development programme, a panel build order and a type test campaign.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Electrical NPD Programme" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "LV Switchgear NPD - PowerLine 630A",
        "project_type": "New Product Development",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "A 630A form-4b low voltage switchboard for the commercial building segment.",
        "phases": [
            {
                "subject": "Definition & Design",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Market Requirement Study",
                        "type": "Design",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Electrical Design",
                        "type": "Design",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Market Requirement Study"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Mechanical Enclosure Design",
                        "type": "Design",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Electrical Design"],
                        "designation": "Tank Fabricator",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Tooling & Sourcing",
                "designation": "Shop Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Busbar System Design",
                        "type": "Design",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Mechanical Enclosure Design"],
                        "designation": "Switchgear Assembler",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "BOM Costing",
                        "type": "Design",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Mechanical Enclosure Design"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Arc-Flash Containment Variant",
                        "type": "Design",
                        "start": 70,
                        "duration": 20,
                        "designation": "Production Manager",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Parked until the arc-fault test slot at the "
                        "external lab frees up.",
                    },
                    {
                        "subject": "Press Tool Order",
                        "type": "Fabrication",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Busbar System Design"],
                        "designation": "Tank Fabricator",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Prototype & Test",
                "designation": "HV Test Engineer",
                "tasks": [
                    {
                        "subject": "Prototype Enclosure Build",
                        "type": "Fabrication",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Mechanical Enclosure Design"],
                        "designation": "Tank Fabricator",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Electrical Safety Audit",
                        "type": "Certification",
                        "start": 130,
                        "duration": 8,
                        "designation": "QC Inspector",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Prototype Assembly",
                        "type": "Assembly",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Prototype Enclosure Build", "Press Tool Order"],
                        "designation": "Switchgear Assembler",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Label & Nameplate Artwork",
                        "type": "Documentation",
                        "start": 150,
                        "duration": 10,
                        "designation": "Dispatch Operator",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Temperature Rise Test",
                        "type": "Testing",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Prototype Assembly"],
                        "designation": "HV Test Engineer",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Release",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Short Circuit Withstand Test",
                        "type": "Testing",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Temperature Rise Test"],
                        "designation": "HV Test Engineer",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Design Freeze Review",
                        "type": "Design",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Short Circuit Withstand Test"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Production Release",
                        "type": "Documentation",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Design Freeze Review"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "11kV Panel Build - Textile Park",
        "project_type": "Panel Build",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "Fourteen 11kV VCB panels for a textile park substation.",
        "phases": [
            {
                "subject": "Engineering",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Customer Drawing Approval",
                        "type": "Design",
                        "start": 0,
                        "duration": 12,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Bill of Material Release",
                        "type": "Design",
                        "start": 5,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Fabrication & Assembly",
                "designation": "Shop Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Enclosure Fabrication",
                        "type": "Fabrication",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Bill of Material Release", "Customer Drawing Approval"],
                        "designation": "Tank Fabricator",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Shop Floor Safety Audit",
                        "type": "Certification",
                        "start": 60,
                        "duration": 6,
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Powder Coating",
                        "type": "Fabrication",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Enclosure Fabrication"],
                        "designation": "Tank Fabricator",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Busbar Assembly",
                        "type": "Assembly",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Powder Coating"],
                        "designation": "Switchgear Assembler",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Test & Despatch",
                "designation": "HV Test Engineer",
                "tasks": [
                    {
                        "subject": "Wiring & Termination",
                        "type": "Assembly",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Busbar Assembly"],
                        "designation": "Switchgear Assembler",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Routine Testing",
                        "type": "Testing",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Busbar Assembly"],
                        "designation": "HV Test Engineer",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Packing & Despatch",
                        "type": "Dispatch",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Wiring & Termination", "Routine Testing"],
                        "designation": "Dispatch Operator",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "IEC 62271 Type Test Campaign",
        "project_type": "Type Testing",
        "priority": "High",
        "start_offset_days": -45,
        "notes": "Type test campaign at CPRI for the 12kV indoor VCB range.",
        "phases": [
            {
                "subject": "Preparation",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Test Plan & Standard Review",
                        "type": "Certification",
                        "start": 0,
                        "duration": 10,
                        "designation": "HV Test Engineer",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Lab Slot Booking",
                        "type": "Certification",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Test Plan & Standard Review"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Customer Witness Confirmation",
                        "type": "Certification",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Lab Slot Booking"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Sample Build",
                "designation": "Shop Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Test Sample Assembly",
                        "type": "Assembly",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Lab Slot Booking"],
                        "designation": "Switchgear Assembler",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Instrumentation Setup",
                        "type": "Testing",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Lab Slot Booking"],
                        "designation": "HV Test Engineer",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Test Campaign",
                "designation": "HV Test Engineer",
                "tasks": [
                    {
                        "subject": "Dielectric Test Series",
                        "type": "Testing",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Customer Witness Confirmation"],
                        "designation": "HV Test Engineer",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Short Time Current Test",
                        "type": "Testing",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Dielectric Test Series", "Test Sample Assembly"],
                        "designation": "HV Test Engineer",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Type Test Report Issue",
                        "type": "Documentation",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Short Time Current Test"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Distribution Transformer NPD - 250 kVA",
        "project_type": "New Product Development",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Electrical NPD Programme",
        "notes": "Opened from the standard NPD programme template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Electrical Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
