"""Seeder: Projects and Tasks for Drones.

An agri-drone development programme, a type certification and a fleet deployment.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Drone NPD Programme" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "Agri-Spray Drone NPD - AgriHawk 8L",
        "project_type": "New Product Development",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "An 8-litre agricultural spraying platform with swappable tank modules.",
        "phases": [
            {
                "subject": "Definition",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Mission Profile Study",
                        "type": "Requirements",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Specification Freeze",
                        "type": "Requirements",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Mission Profile Study"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Spray Boom Design",
                        "type": "Design",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Specification Freeze"],
                        "designation": "Frame Assembly Technician",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Design & Sourcing",
                "designation": "Assembly Supervisor",
                "tasks": [
                    {
                        "subject": "Airframe Structural Design",
                        "type": "Design",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Spray Boom Design"],
                        "designation": "Frame Assembly Technician",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Avionics Architecture",
                        "type": "Design",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Spray Boom Design"],
                        "designation": "Avionics Technician",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "LiDAR Terrain-Follow Module",
                        "type": "Design",
                        "start": 70,
                        "duration": 20,
                        "designation": "Avionics Technician",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Deferred to the next revision after the sensor lead "
                        "time doubled.",
                    },
                    {
                        "subject": "Motor & ESC Sourcing",
                        "type": "Production",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Airframe Structural Design"],
                        "designation": "PCB Assembly Technician",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Prototype & Flight Test",
                "designation": "Flight Test Pilot",
                "tasks": [
                    {
                        "subject": "Prototype Airframe Build",
                        "type": "Prototyping",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Spray Boom Design"],
                        "designation": "Frame Assembly Technician",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Battery Handling Safety Audit",
                        "type": "Certification",
                        "start": 130,
                        "duration": 8,
                        "designation": "QC Inspector",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Bench Integration Test",
                        "type": "Prototyping",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Prototype Airframe Build", "Motor & ESC Sourcing"],
                        "designation": "Avionics Technician",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Spray Pattern Calibration",
                        "type": "Firmware",
                        "start": 150,
                        "duration": 10,
                        "designation": "Firmware Calibration Engineer",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Flight Test Campaign",
                        "type": "Flight Test",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Bench Integration Test"],
                        "designation": "Flight Test Pilot",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Release",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Design Freeze Review",
                        "type": "Design",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Flight Test Campaign"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Pilot Production Batch",
                        "type": "Production",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Design Freeze Review"],
                        "designation": "Assembly Supervisor",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Production Release",
                        "type": "Documentation",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Pilot Production Batch"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "DGCA Type Certification - SurveyWing",
        "project_type": "Certification",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "Type certification for the SurveyWing fixed-wing mapping platform.",
        "phases": [
            {
                "subject": "Dossier",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Compliance Matrix",
                        "type": "Certification",
                        "start": 0,
                        "duration": 12,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Design Data Pack",
                        "type": "Certification",
                        "start": 5,
                        "duration": 10,
                        "designation": "Avionics Technician",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Test Campaign",
                "designation": "Flight Test Pilot",
                "tasks": [
                    {
                        "subject": "EMI/EMC Testing",
                        "type": "Certification",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Design Data Pack", "Compliance Matrix"],
                        "designation": "Avionics Technician",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Range Safety Audit",
                        "type": "Certification",
                        "start": 60,
                        "duration": 6,
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Endurance Flight Trials",
                        "type": "Flight Test",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["EMI/EMC Testing"],
                        "designation": "Flight Test Pilot",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Failure Mode Trials",
                        "type": "Flight Test",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Endurance Flight Trials"],
                        "designation": "Flight Test Pilot",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Submission",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Flight Manual Preparation",
                        "type": "Documentation",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Failure Mode Trials"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "DGCA Submission",
                        "type": "Certification",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Failure Mode Trials"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Certificate Issue",
                        "type": "Certification",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Flight Manual Preparation", "DGCA Submission"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Survey Fleet Deployment - NHAI Corridor",
        "project_type": "Fleet Deployment",
        "priority": "High",
        "start_offset_days": -45,
        "notes": "Twelve mapping drones and two ground stations for a highway survey contract.",
        "phases": [
            {
                "subject": "Readiness",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Corridor Requirement Study",
                        "type": "Requirements",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Fleet Configuration Plan",
                        "type": "Design",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Corridor Requirement Study"],
                        "designation": "Avionics Technician",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Customer Sign-off",
                        "type": "Requirements",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Fleet Configuration Plan"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Build & Configure",
                "designation": "Assembly Supervisor",
                "tasks": [
                    {
                        "subject": "Airframe Build Batch",
                        "type": "Production",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Fleet Configuration Plan"],
                        "designation": "Frame Assembly Technician",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Ground Station Setup",
                        "type": "Production",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Fleet Configuration Plan"],
                        "designation": "Avionics Technician",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Field Rollout",
                "designation": "Flight Test Pilot",
                "tasks": [
                    {
                        "subject": "Firmware Fleet Calibration",
                        "type": "Firmware",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Customer Sign-off"],
                        "designation": "Firmware Calibration Engineer",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Field Acceptance Flights",
                        "type": "Flight Test",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Firmware Fleet Calibration", "Airframe Build Batch"],
                        "designation": "Flight Test Pilot",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Operator Training & Handover",
                        "type": "Documentation",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Field Acceptance Flights"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Payload Variant NPD - Thermal Pod",
        "project_type": "New Product Development",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Drone NPD Programme",
        "notes": "Thermal payload variant, opened from the standard NPD programme template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Drones Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
