"""Seeder: Projects and Tasks for Distribution.

A new distribution centre, a route expansion and a festive trade programme.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Depot Commissioning" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "Regional DC Commissioning - Nagpur",
        "project_type": "Warehouse Setup",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "42,000 sq ft regional distribution centre serving the Vidarbha belt.",
        "phases": [
            {
                "subject": "Site & Approvals",
                "designation": "Warehouse Manager",
                "tasks": [
                    {
                        "subject": "Location Survey",
                        "type": "Site Selection",
                        "start": 0,
                        "duration": 10,
                        "designation": "Warehouse Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Lease Negotiation",
                        "type": "Site Selection",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Location Survey"],
                        "designation": "Accounts Executive",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Fire & Trade Licences",
                        "type": "Site Selection",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Lease Negotiation"],
                        "designation": "Accounts Executive",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Fit-out",
                "designation": "Dispatch Supervisor",
                "tasks": [
                    {
                        "subject": "Racking Order",
                        "type": "Fit-out",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Fire & Trade Licences"],
                        "designation": "Warehouse Manager",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Material Handling Equipment Order",
                        "type": "Fit-out",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Fire & Trade Licences"],
                        "designation": "Dispatch Supervisor",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Cold Room Package",
                        "type": "Fit-out",
                        "start": 70,
                        "duration": 20,
                        "designation": "Warehouse Manager",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Deferred — the chilled range stayed with the "
                        "third-party cold chain.",
                    },
                    {
                        "subject": "Dock Leveller Supply",
                        "type": "Fit-out",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Racking Order"],
                        "designation": "Dispatch Supervisor",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Systems & Staffing",
                "designation": "Warehouse Manager",
                "tasks": [
                    {
                        "subject": "Civil & Flooring Work",
                        "type": "Fit-out",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Fire & Trade Licences"],
                        "designation": "Dispatch Supervisor",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Fire Safety Audit",
                        "type": "Audit",
                        "start": 130,
                        "duration": 8,
                        "designation": "Warehouse Manager",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Racking Installation",
                        "type": "Fit-out",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Civil & Flooring Work", "Dock Leveller Supply"],
                        "designation": "Warehouse Picker",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Signage & Bin Labelling",
                        "type": "Fit-out",
                        "start": 150,
                        "duration": 10,
                        "designation": "Warehouse Picker",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "WMS Configuration",
                        "type": "Systems",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Racking Installation"],
                        "designation": "Warehouse Manager",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Go-Live",
                "designation": "Warehouse Manager",
                "tasks": [
                    {
                        "subject": "Picker & Driver Recruitment",
                        "type": "Recruitment",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["WMS Configuration"],
                        "designation": "Dispatch Supervisor",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Opening Stock Transfer",
                        "type": "Inventory",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Picker & Driver Recruitment"],
                        "designation": "Warehouse Picker",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Depot Go-Live",
                        "type": "Systems",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Opening Stock Transfer"],
                        "designation": "Warehouse Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Tier-2 Route Expansion - Vidarbha",
        "project_type": "Route Expansion",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "Twelve new beats across Amravati, Akola and Yavatmal.",
        "phases": [
            {
                "subject": "Market Study",
                "designation": "Sales Representative",
                "tasks": [
                    {
                        "subject": "Territory Potential Study",
                        "type": "Site Selection",
                        "start": 0,
                        "duration": 12,
                        "designation": "Sales Representative",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Retailer Universe Mapping",
                        "type": "Site Selection",
                        "start": 5,
                        "duration": 10,
                        "designation": "Sales Representative",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Build-out",
                "designation": "Dispatch Supervisor",
                "tasks": [
                    {
                        "subject": "Beat Plan Design",
                        "type": "Systems",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Retailer Universe Mapping", "Territory Potential Study"],
                        "designation": "Dispatch Supervisor",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Vehicle Fitness Audit",
                        "type": "Audit",
                        "start": 60,
                        "duration": 6,
                        "designation": "Delivery Driver",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Driver & Salesman Hiring",
                        "type": "Recruitment",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Beat Plan Design"],
                        "designation": "Dispatch Supervisor",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Route Software Setup",
                        "type": "Systems",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Driver & Salesman Hiring"],
                        "designation": "Accounts Executive",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Launch",
                "designation": "Sales Representative",
                "tasks": [
                    {
                        "subject": "Field Training",
                        "type": "Training",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Route Software Setup"],
                        "designation": "Sales Representative",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Launch Stock Allocation",
                        "type": "Inventory",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Route Software Setup"],
                        "designation": "Warehouse Picker",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "First Beat Cycle",
                        "type": "Marketing",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Field Training", "Launch Stock Allocation"],
                        "designation": "Sales Representative",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Festive Trade Programme - Diwali",
        "project_type": "Trade Programme",
        "priority": "High",
        "start_offset_days": -45,
        "notes": "Retailer scheme and stock build-up for the festive quarter.",
        "phases": [
            {
                "subject": "Scheme Design",
                "designation": "Sales Representative",
                "tasks": [
                    {
                        "subject": "Category Demand Forecast",
                        "type": "Marketing",
                        "start": 0,
                        "duration": 10,
                        "designation": "Sales Representative",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Scheme & Margin Design",
                        "type": "Marketing",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Category Demand Forecast"],
                        "designation": "Sales Representative",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Principal Approval",
                        "type": "Marketing",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Scheme & Margin Design"],
                        "designation": "Accounts Executive",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Stock & Systems",
                "designation": "Warehouse Manager",
                "tasks": [
                    {
                        "subject": "Festive Stock Build-up",
                        "type": "Inventory",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Scheme & Margin Design"],
                        "designation": "Warehouse Manager",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Combo Pack Assembly",
                        "type": "Inventory",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Scheme & Margin Design"],
                        "designation": "Warehouse Picker",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Execution",
                "designation": "Sales Representative",
                "tasks": [
                    {
                        "subject": "Retailer Communication Drive",
                        "type": "Marketing",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Principal Approval"],
                        "designation": "Sales Representative",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Secondary Sales Tracking",
                        "type": "Systems",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Retailer Communication Drive", "Festive Stock Build-up"],
                        "designation": "Accounts Executive",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Claim Reconciliation",
                        "type": "Audit",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Secondary Sales Tracking"],
                        "designation": "Accounts Executive",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Satellite Depot Setup - Aurangabad",
        "project_type": "Warehouse Setup",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Depot Commissioning",
        "notes": "Small-format depot, generated from the standard commissioning template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Distribution Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
