"""Seeder: Projects and Tasks for EPC.

A substation package, a warehouse shell and a treatment plant upgrade.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "MEP Retrofit Package" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "220kV Substation Package - Nashik",
        "project_type": "Turnkey EPC",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "Turnkey 220/33kV substation for the Nashik industrial corridor.",
        "phases": [
            {
                "subject": "Engineering & Approvals",
                "designation": "Project Manager",
                "tasks": [
                    {
                        "subject": "Topographic Survey",
                        "type": "Survey",
                        "start": 0,
                        "duration": 10,
                        "designation": "Site Engineer",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Foundation Design",
                        "type": "Design",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Topographic Survey"],
                        "designation": "Project Manager",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Statutory Approvals",
                        "type": "Approval",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Foundation Design"],
                        "designation": "Quantity Surveyor",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Procurement",
                "designation": "Quantity Surveyor",
                "tasks": [
                    {
                        "subject": "Transformer Purchase Order",
                        "type": "Procurement",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Statutory Approvals"],
                        "designation": "Quantity Surveyor",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Switchgear Purchase Order",
                        "type": "Procurement",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Statutory Approvals"],
                        "designation": "Quantity Surveyor",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Diesel Generator Package",
                        "type": "Procurement",
                        "start": 70,
                        "duration": 20,
                        "designation": "Quantity Surveyor",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Dropped after the client extended the grid feeder.",
                    },
                    {
                        "subject": "Cable & Conductor Supply",
                        "type": "Procurement",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Transformer Purchase Order"],
                        "designation": "Foreman",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Civil & Erection",
                "designation": "Site Engineer",
                "tasks": [
                    {
                        "subject": "Foundation Casting",
                        "type": "Civil Works",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Statutory Approvals"],
                        "designation": "Foreman",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Safety Audit - Erection Phase",
                        "type": "Safety",
                        "start": 130,
                        "duration": 8,
                        "designation": "Safety Officer",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Structure Erection",
                        "type": "Civil Works",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Foundation Casting", "Cable & Conductor Supply"],
                        "designation": "Site Engineer",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Punch List Closure",
                        "type": "Civil Works",
                        "start": 150,
                        "duration": 10,
                        "designation": "Carpenter",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Transformer Installation",
                        "type": "MEP",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Structure Erection"],
                        "designation": "Electrician",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Testing & Handover",
                "designation": "Project Manager",
                "tasks": [
                    {
                        "subject": "Pre-commissioning Checks",
                        "type": "Testing",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Transformer Installation"],
                        "designation": "Site Engineer",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Protection Relay Testing",
                        "type": "Testing",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Pre-commissioning Checks"],
                        "designation": "Electrician",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Client Handover",
                        "type": "Handover",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Protection Relay Testing"],
                        "designation": "Project Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Industrial Warehouse Shell - Bhiwandi",
        "project_type": "Civil Works",
        "priority": "Medium",
        "start_offset_days": -95,
        "notes": "48,000 sq ft pre-engineered warehouse shell with dock levellers.",
        "phases": [
            {
                "subject": "Site Preparation",
                "designation": "Site Engineer",
                "tasks": [
                    {
                        "subject": "Land Survey & Levelling",
                        "type": "Survey",
                        "start": 0,
                        "duration": 12,
                        "designation": "Site Engineer",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Soil Investigation",
                        "type": "Survey",
                        "start": 5,
                        "duration": 10,
                        "designation": "Quantity Surveyor",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Structure",
                "designation": "Foreman",
                "tasks": [
                    {
                        "subject": "Pile Foundation",
                        "type": "Civil Works",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Soil Investigation", "Land Survey & Levelling"],
                        "designation": "Foreman",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Monthly Safety Audit",
                        "type": "Safety",
                        "start": 60,
                        "duration": 6,
                        "designation": "Safety Officer",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "PEB Column Erection",
                        "type": "Civil Works",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Pile Foundation"],
                        "designation": "Foreman",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Roof Sheeting",
                        "type": "Civil Works",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["PEB Column Erection"],
                        "designation": "Carpenter",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Finishing & Handover",
                "designation": "Project Manager",
                "tasks": [
                    {
                        "subject": "Flooring & Screed",
                        "type": "Civil Works",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Roof Sheeting"],
                        "designation": "Carpenter",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Dock Leveller Installation",
                        "type": "MEP",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Roof Sheeting"],
                        "designation": "Electrician",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Snag List & Handover",
                        "type": "Handover",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Flooring & Screed", "Dock Leveller Installation"],
                        "designation": "Project Manager",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Water Treatment Plant Upgrade - Pune",
        "project_type": "Turnkey EPC",
        "priority": "High",
        "start_offset_days": -45,
        "notes": "Capacity upgrade from 800 to 1,400 KLD with tertiary treatment.",
        "phases": [
            {
                "subject": "Process Design",
                "designation": "Project Manager",
                "tasks": [
                    {
                        "subject": "Effluent Characterisation",
                        "type": "Survey",
                        "start": 0,
                        "duration": 10,
                        "designation": "Site Engineer",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Process Flow Design",
                        "type": "Design",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Effluent Characterisation"],
                        "designation": "Project Manager",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Pollution Board Clearance",
                        "type": "Approval",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Process Flow Design"],
                        "designation": "Quantity Surveyor",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Equipment Supply",
                "designation": "Quantity Surveyor",
                "tasks": [
                    {
                        "subject": "Clarifier Purchase Order",
                        "type": "Procurement",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Process Flow Design"],
                        "designation": "Quantity Surveyor",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Dosing Pump Supply",
                        "type": "Procurement",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Process Flow Design"],
                        "designation": "Foreman",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Installation & Commissioning",
                "designation": "Site Engineer",
                "tasks": [
                    {
                        "subject": "Tank Civil Works",
                        "type": "Civil Works",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Pollution Board Clearance"],
                        "designation": "Foreman",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Piping & Instrumentation",
                        "type": "MEP",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Tank Civil Works", "Clarifier Purchase Order"],
                        "designation": "Plumber",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Trial Run & Handover",
                        "type": "Testing",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Piping & Instrumentation"],
                        "designation": "Project Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Metro Depot MEP Fit-out - Wadala",
        "project_type": "MEP Retrofit",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "MEP Retrofit Package",
        "notes": "Generated from the MEP Retrofit Package template at kick-off.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "EPC Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
