"""Seeder: Projects and Tasks for Vanilla.

Generic internal and customer-facing projects on the clean-slate site.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Standard Delivery Programme" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "ERP Rollout - Phase 1",
        "project_type": "Internal",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "Finance, stock and sales go-live across the head office and the main warehouse.",
        "phases": [
            {
                "subject": "Discovery",
                "designation": "General Manager",
                "tasks": [
                    {
                        "subject": "Stakeholder Interviews",
                        "type": "Analysis",
                        "start": 0,
                        "duration": 10,
                        "designation": "General Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Requirement Document",
                        "type": "Analysis",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Stakeholder Interviews"],
                        "designation": "General Manager",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Scope Sign-off",
                        "type": "Review",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Requirement Document"],
                        "designation": "General Manager",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Design & Setup",
                "designation": "Accountant",
                "tasks": [
                    {
                        "subject": "Chart of Accounts Design",
                        "type": "Planning",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Scope Sign-off"],
                        "designation": "Accountant",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Item & Warehouse Setup",
                        "type": "Implementation",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Scope Sign-off"],
                        "designation": "Warehouse Associate",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Manufacturing Module Rollout",
                        "type": "Planning",
                        "start": 70,
                        "duration": 20,
                        "designation": "General Manager",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Moved to phase 2 once the scope was trimmed to "
                        "finance and stock.",
                    },
                    {
                        "subject": "Customer & Supplier Import",
                        "type": "Implementation",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Chart of Accounts Design"],
                        "designation": "Sales Representative",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Build & Test",
                "designation": "General Manager",
                "tasks": [
                    {
                        "subject": "Opening Balance Migration",
                        "type": "Implementation",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Scope Sign-off"],
                        "designation": "Accountant",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Access Control Review",
                        "type": "Review",
                        "start": 130,
                        "duration": 8,
                        "designation": "Accountant",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "System Testing",
                        "type": "Testing",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Opening Balance Migration", "Customer & Supplier Import"],
                        "designation": "General Manager",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Report Pack Setup",
                        "type": "Documentation",
                        "start": 150,
                        "duration": 10,
                        "designation": "Accountant",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "User Acceptance Testing",
                        "type": "Testing",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["System Testing"],
                        "designation": "Sales Representative",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Cutover",
                "designation": "General Manager",
                "tasks": [
                    {
                        "subject": "Key User Training",
                        "type": "Training",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["User Acceptance Testing"],
                        "designation": "General Manager",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Cutover Rehearsal",
                        "type": "Testing",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Key User Training"],
                        "designation": "Accountant",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Go-Live",
                        "type": "Documentation",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Cutover Rehearsal"],
                        "designation": "General Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Website Revamp",
        "project_type": "External",
        "priority": "Medium",
        "start_offset_days": -95,
        "notes": "A rebuilt public site with an online catalogue and enquiry capture.",
        "phases": [
            {
                "subject": "Discovery",
                "designation": "General Manager",
                "tasks": [
                    {
                        "subject": "Content Audit",
                        "type": "Analysis",
                        "start": 0,
                        "duration": 12,
                        "designation": "Sales Representative",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Competitor Review",
                        "type": "Analysis",
                        "start": 5,
                        "duration": 10,
                        "designation": "Sales Representative",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Build",
                "designation": "Sales Representative",
                "tasks": [
                    {
                        "subject": "Design Approval",
                        "type": "Review",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Competitor Review", "Content Audit"],
                        "designation": "General Manager",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Accessibility Review",
                        "type": "Review",
                        "start": 60,
                        "duration": 6,
                        "designation": "General Manager",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Page Build",
                        "type": "Implementation",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Design Approval"],
                        "designation": "Sales Representative",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Catalogue Data Load",
                        "type": "Implementation",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Page Build"],
                        "designation": "Warehouse Associate",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Launch",
                "designation": "General Manager",
                "tasks": [
                    {
                        "subject": "Enquiry Form Integration",
                        "type": "Implementation",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Catalogue Data Load"],
                        "designation": "Sales Representative",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Cross-browser Testing",
                        "type": "Testing",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Catalogue Data Load"],
                        "designation": "General Manager",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Site Launch",
                        "type": "Documentation",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Enquiry Form Integration", "Cross-browser Testing"],
                        "designation": "General Manager",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Office Relocation",
        "project_type": "Internal",
        "priority": "Medium",
        "start_offset_days": -45,
        "notes": "Moving head office to the new premises with minimal downtime.",
        "phases": [
            {
                "subject": "Planning",
                "designation": "General Manager",
                "tasks": [
                    {
                        "subject": "Space Requirement Study",
                        "type": "Analysis",
                        "start": 0,
                        "duration": 10,
                        "designation": "General Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Lease Finalisation",
                        "type": "Planning",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Space Requirement Study"],
                        "designation": "Accountant",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Board Approval",
                        "type": "Review",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Lease Finalisation"],
                        "designation": "General Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Preparation",
                "designation": "Warehouse Associate",
                "tasks": [
                    {
                        "subject": "Furniture & Fit-out Order",
                        "type": "Implementation",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Lease Finalisation"],
                        "designation": "Warehouse Associate",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Network & Telephony Setup",
                        "type": "Implementation",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Lease Finalisation"],
                        "designation": "General Manager",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Move",
                "designation": "General Manager",
                "tasks": [
                    {
                        "subject": "Packing & Labelling",
                        "type": "Implementation",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Board Approval"],
                        "designation": "Warehouse Associate",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Move Weekend Execution",
                        "type": "Implementation",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Packing & Labelling", "Furniture & Fit-out Order"],
                        "designation": "Warehouse Associate",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Post-move Review",
                        "type": "Review",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Move Weekend Execution"],
                        "designation": "General Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Customer Portal Pilot",
        "project_type": "External",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Standard Delivery Programme",
        "notes": "Pilot customer portal, opened from the standard delivery template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Vanilla Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
