"""Seeder: Projects and Tasks for Alpha Abrasives.

A new grinding wheel line commissioning, an ISI certification campaign for
cutting wheels, and a Middle East export buyer onboarding programme — one
project per line of the hybrid business. Each sits at a different stage of
its life, and the last one is generated by ERPNext itself from the
"Abrasive NPD Programme" Project Template.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "New Grinding Wheel Line Commissioning",
        "project_type": "New Product Development",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "Commission the second press and curing oven for the 150mm/230mm "
        "grinding wheel range.",
        "phases": [
            {
                "subject": "Planning & Design",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Capacity & Layout Study",
                        "type": "Design",
                        "start": 0,
                        "duration": 12,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Formulation Finalisation",
                        "type": "Design",
                        "start": 12,
                        "duration": 18,
                        "depends_on": ["Capacity & Layout Study"],
                        "designation": "Mixing & Bonding Technician",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Alternate Bond Chemistry Trial",
                        "type": "Design",
                        "start": 30,
                        "duration": 15,
                        "designation": "Mixing & Bonding Technician",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Parked in favour of the proven vitrified bond mix.",
                    },
                ],
            },
            {
                "subject": "Equipment Commissioning",
                "designation": "Shop Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Hydraulic Press Installation",
                        "type": "Production",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Formulation Finalisation"],
                        "designation": "Press Operator",
                        "priority": "High",
                        "hours": 160,
                    },
                    {
                        "subject": "Curing Oven Installation",
                        "type": "Production",
                        "start": 30,
                        "duration": 20,
                        "designation": "Curing Oven Operator",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Utility Safety Audit",
                        "type": "Certification",
                        "start": 55,
                        "duration": 8,
                        "designation": "QC Inspector",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                ],
            },
            {
                "subject": "Trial Run & Qualification",
                "designation": "QC Inspector",
                "tasks": [
                    {
                        "subject": "Trial Batch Production",
                        "type": "Production",
                        "start": 63,
                        "duration": 20,
                        "depends_on": ["Hydraulic Press Installation", "Curing Oven Installation"],
                        "designation": "Press Operator",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Burst/RPM Safety Qualification",
                        "type": "Testing",
                        "start": 83,
                        "duration": 18,
                        "depends_on": ["Trial Batch Production"],
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Wheel Balance & Bond Hardness Sign-off",
                        "type": "Testing",
                        "start": 83,
                        "duration": 15,
                        "depends_on": ["Trial Batch Production"],
                        "designation": "QC Inspector",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Release",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Line Sign-off & Production Release",
                        "type": "Documentation",
                        "start": 101,
                        "duration": 10,
                        "depends_on": [
                            "Burst/RPM Safety Qualification",
                            "Wheel Balance & Bond Hardness Sign-off",
                        ],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "ISI Certification - Cutting Wheels",
        "project_type": "Quality Certification",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "ISI mark certification for the 100mm/115mm/300mm cutting wheel range.",
        "phases": [
            {
                "subject": "Preparation",
                "designation": "QC Inspector",
                "tasks": [
                    {
                        "subject": "Standard & Test Plan Review",
                        "type": "Certification",
                        "start": 0,
                        "duration": 10,
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Sample Batch Preparation",
                        "type": "Production",
                        "start": 10,
                        "duration": 15,
                        "depends_on": ["Standard & Test Plan Review"],
                        "designation": "Press Operator",
                        "priority": "High",
                        "hours": 70,
                    },
                ],
            },
            {
                "subject": "Lab Testing",
                "designation": "QC Inspector",
                "tasks": [
                    {
                        "subject": "Burst/RPM Safety Test Series",
                        "type": "Testing",
                        "start": 25,
                        "duration": 22,
                        "depends_on": ["Sample Batch Preparation"],
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 90,
                    },
                    {
                        "subject": "Grit Consistency Test Series",
                        "type": "Testing",
                        "start": 25,
                        "duration": 18,
                        "depends_on": ["Sample Batch Preparation"],
                        "designation": "QC Inspector",
                        "priority": "Medium",
                        "hours": 60,
                    },
                ],
            },
            {
                "subject": "Certification",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "BIS Factory Audit",
                        "type": "Certification",
                        "start": 47,
                        "duration": 15,
                        "depends_on": [
                            "Burst/RPM Safety Test Series",
                            "Grit Consistency Test Series",
                        ],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                    },
                    {
                        "subject": "ISI Mark Grant",
                        "type": "Documentation",
                        "start": 62,
                        "duration": 10,
                        "depends_on": ["BIS Factory Audit"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 12,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Export Buyer Onboarding - Middle East",
        "project_type": "Export Market Development",
        "priority": "Medium",
        "start_offset_days": -45,
        "notes": "Onboard two UAE-based distributors for the wheel/disc/belt export range.",
        "phases": [
            {
                "subject": "Qualification",
                "designation": "Import & Procurement Executive",
                "tasks": [
                    {
                        "subject": "Distributor Due Diligence",
                        "type": "Onboarding",
                        "start": 0,
                        "duration": 15,
                        "designation": "Import & Procurement Executive",
                        "priority": "Medium",
                        "hours": 30,
                    },
                    {
                        "subject": "Sample Kit Dispatch",
                        "type": "Dispatch",
                        "start": 15,
                        "duration": 10,
                        "depends_on": ["Distributor Due Diligence"],
                        "designation": "Dispatch Operator",
                        "priority": "Medium",
                        "hours": 12,
                    },
                ],
            },
            {
                "subject": "Export Documentation",
                "designation": "Import & Procurement Executive",
                "tasks": [
                    {
                        "subject": "Export Licence & Compliance Filing",
                        "type": "Documentation",
                        "start": 25,
                        "duration": 18,
                        "depends_on": ["Sample Kit Dispatch"],
                        "designation": "Import & Procurement Executive",
                        "priority": "High",
                        "hours": 40,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Pricing & Distributor Agreement",
                        "type": "Documentation",
                        "start": 25,
                        "duration": 15,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 20,
                    },
                ],
            },
            {
                "subject": "Rollout",
                "designation": "Import & Procurement Executive",
                "tasks": [
                    {
                        "subject": "Distributor Agreement Signing",
                        "type": "Onboarding",
                        "start": 40,
                        "duration": 10,
                        "depends_on": ["Export Licence & Compliance Filing"],
                        "designation": "Import & Procurement Executive",
                        "priority": "High",
                        "hours": 16,
                    },
                    {
                        "subject": "Compliance Document Review",
                        "type": "Documentation",
                        "start": 42,
                        "duration": 12,
                        "depends_on": ["Distributor Agreement Signing"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 20,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "First Container Shipment",
                        "type": "Dispatch",
                        "start": 55,
                        "duration": 15,
                        "depends_on": ["Compliance Document Review"],
                        "designation": "Dispatch Operator",
                        "priority": "Medium",
                        "hours": 24,
                    },
                ],
            },
        ],
    },
    {
        "name": "Coated Belt NPD - Wide Belt Range",
        "project_type": "New Product Development",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 145,
        "template": "Abrasive NPD Programme",
        "notes": "Opened from the standard NPD programme template for a new wide-belt "
        "coated abrasive range.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Abrasives Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
