"""Seeder: Projects and Tasks for Crockery.

A dinnerware launch, a kiln rebuild and a flagship store rollout.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Collection Development" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "Stoneware Dinnerware Launch - Terra Series",
        "project_type": "Collection Launch",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "A 16-piece reactive-glaze stoneware range for the premium retail channel.",
        "phases": [
            {
                "subject": "Concept & Design",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Concept Sketches",
                        "type": "Design",
                        "start": 0,
                        "duration": 10,
                        "designation": "Throwing Artisan",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Form Development",
                        "type": "Design",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Concept Sketches"],
                        "designation": "Throwing Artisan",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Colourway Approval",
                        "type": "Design",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Form Development"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Tooling & Glaze",
                "designation": "Kiln Supervisor",
                "tasks": [
                    {
                        "subject": "Master Mould Production",
                        "type": "Mould Making",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Colourway Approval"],
                        "designation": "Casting Operator",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Working Mould Set",
                        "type": "Mould Making",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Colourway Approval"],
                        "designation": "Casting Operator",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Hand-painted Rim Variant",
                        "type": "Design",
                        "start": 70,
                        "duration": 20,
                        "designation": "Glazing Technician",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Cut from the range after costing put it above the "
                        "target shelf price.",
                    },
                    {
                        "subject": "Reactive Glaze Trials",
                        "type": "Glaze Development",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Master Mould Production"],
                        "designation": "Glazing Technician",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Pilot Production",
                "designation": "Kiln Supervisor",
                "tasks": [
                    {
                        "subject": "First Casting Run",
                        "type": "Production",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Colourway Approval"],
                        "designation": "Casting Operator",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Kiln Safety Audit",
                        "type": "Inspection",
                        "start": 130,
                        "duration": 8,
                        "designation": "Kiln Supervisor",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Bisque Firing Trial",
                        "type": "Production",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["First Casting Run", "Reactive Glaze Trials"],
                        "designation": "Kiln Operator",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Packaging Design",
                        "type": "Marketing",
                        "start": 150,
                        "duration": 10,
                        "designation": "Packaging Operator",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Glost Firing Run",
                        "type": "Production",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Bisque Firing Trial"],
                        "designation": "Kiln Operator",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Launch",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Defect Sorting & Grading",
                        "type": "Inspection",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Glost Firing Run"],
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Catalogue Photography",
                        "type": "Marketing",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Defect Sorting & Grading"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Trade Launch",
                        "type": "Marketing",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Catalogue Photography"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Kiln-2 Refractory Rebuild",
        "project_type": "Kiln Project",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "Full re-lining of the No.2 shuttle kiln after 11 years of service.",
        "phases": [
            {
                "subject": "Assessment",
                "designation": "Kiln Supervisor",
                "tasks": [
                    {
                        "subject": "Refractory Condition Survey",
                        "type": "Inspection",
                        "start": 0,
                        "duration": 12,
                        "designation": "Kiln Supervisor",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Rebuild Scope & Budget",
                        "type": "Design",
                        "start": 5,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Rebuild",
                "designation": "Kiln Supervisor",
                "tasks": [
                    {
                        "subject": "Old Lining Demolition",
                        "type": "Installation",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Rebuild Scope & Budget", "Refractory Condition Survey"],
                        "designation": "Kiln Operator",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Hot Work Safety Audit",
                        "type": "Inspection",
                        "start": 60,
                        "duration": 6,
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "New Lining Installation",
                        "type": "Installation",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Old Lining Demolition"],
                        "designation": "Kiln Operator",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Burner Overhaul",
                        "type": "Installation",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["New Lining Installation"],
                        "designation": "Kiln Supervisor",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Recommissioning",
                "designation": "Kiln Operator",
                "tasks": [
                    {
                        "subject": "Temperature Profiling",
                        "type": "Inspection",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Burner Overhaul"],
                        "designation": "Kiln Supervisor",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Trial Firing",
                        "type": "Production",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Burner Overhaul"],
                        "designation": "Kiln Operator",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Handover to Production",
                        "type": "Inspection",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Temperature Profiling", "Trial Firing"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Flagship Store Rollout - Bandra",
        "project_type": "Retail Rollout",
        "priority": "Medium",
        "start_offset_days": -45,
        "notes": "First own-brand retail store, 1,800 sq ft on Linking Road.",
        "phases": [
            {
                "subject": "Site & Design",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Site Finalisation",
                        "type": "Design",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Store Layout Design",
                        "type": "Design",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Site Finalisation"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Landlord Approval",
                        "type": "Design",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Store Layout Design"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Fit-out",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Display Fixture Order",
                        "type": "Installation",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Store Layout Design"],
                        "designation": "Packaging Operator",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Merchandising Plan",
                        "type": "Marketing",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Store Layout Design"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Opening",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Interior Fit-out",
                        "type": "Installation",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Landlord Approval"],
                        "designation": "Casting Operator",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Stock Transfer & Display",
                        "type": "Production",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Interior Fit-out", "Display Fixture Order"],
                        "designation": "Packaging Operator",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Store Opening",
                        "type": "Marketing",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Stock Transfer & Display"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Glazed Serveware Launch - Monsoon",
        "project_type": "Collection Launch",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Collection Development",
        "notes": "Second-half range, started from the standard collection template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Crockery Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
