"""Seeder: Projects and Tasks for Healthcare.

An OPD wing commissioning, an accreditation programme and a clinical launch.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Clinical Facility Commissioning" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "New OPD Wing Commissioning",
        "project_type": "Facility Setup",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "A 14-consult-room outpatient wing with an in-house sample collection point.",
        "phases": [
            {
                "subject": "Planning & Approvals",
                "designation": "Hospital Administrator",
                "tasks": [
                    {
                        "subject": "Needs Assessment",
                        "type": "Planning",
                        "start": 0,
                        "duration": 10,
                        "designation": "Hospital Administrator",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Layout & Patient Flow Design",
                        "type": "Planning",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Needs Assessment"],
                        "designation": "Hospital Administrator",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Fire & Health Clearance",
                        "type": "Documentation",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Layout & Patient Flow Design"],
                        "designation": "Billing Executive",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Build-out",
                "designation": "Store Manager",
                "tasks": [
                    {
                        "subject": "Equipment Specification",
                        "type": "Equipment",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Fire & Health Clearance"],
                        "designation": "Store Manager",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Equipment Purchase Order",
                        "type": "Equipment",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Fire & Health Clearance"],
                        "designation": "Store Manager",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Digital X-Ray Room",
                        "type": "Equipment",
                        "start": 70,
                        "duration": 20,
                        "designation": "Hospital Administrator",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Held back pending the AERB licence for the second "
                        "radiology room.",
                    },
                    {
                        "subject": "Furniture & Fixture Order",
                        "type": "Equipment",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Equipment Specification"],
                        "designation": "Store Manager",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Equipment & Staffing",
                "designation": "Hospital Administrator",
                "tasks": [
                    {
                        "subject": "Civil & Services Work",
                        "type": "Civil Works",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Fire & Health Clearance"],
                        "designation": "Store Manager",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Infection Control Audit",
                        "type": "Audit",
                        "start": 130,
                        "duration": 8,
                        "designation": "Staff Nurse",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Consult Room Fit-out",
                        "type": "Civil Works",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Civil & Services Work", "Furniture & Fixture Order"],
                        "designation": "Store Manager",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Signage & Wayfinding",
                        "type": "Civil Works",
                        "start": 150,
                        "duration": 10,
                        "designation": "Billing Executive",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Equipment Installation",
                        "type": "Equipment",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Consult Room Fit-out"],
                        "designation": "Lab Technician",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Go-Live",
                "designation": "Hospital Administrator",
                "tasks": [
                    {
                        "subject": "Nursing Staff Recruitment",
                        "type": "Recruitment",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Equipment Installation"],
                        "designation": "Staff Nurse",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Protocol & HIS Training",
                        "type": "Training",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Nursing Staff Recruitment"],
                        "designation": "Staff Nurse",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "OPD Wing Go-Live",
                        "type": "Launch",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Protocol & HIS Training"],
                        "designation": "Hospital Administrator",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "NABH Accreditation Programme",
        "project_type": "Accreditation",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "Full NABH entry-level to full accreditation upgrade across all departments.",
        "phases": [
            {
                "subject": "Assessment",
                "designation": "Hospital Administrator",
                "tasks": [
                    {
                        "subject": "Gap Assessment",
                        "type": "Audit",
                        "start": 0,
                        "duration": 12,
                        "designation": "Hospital Administrator",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Action Plan",
                        "type": "Planning",
                        "start": 5,
                        "duration": 10,
                        "designation": "Hospital Administrator",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Implementation",
                "designation": "Staff Nurse",
                "tasks": [
                    {
                        "subject": "Policy & SOP Drafting",
                        "type": "Documentation",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Action Plan", "Gap Assessment"],
                        "designation": "Staff Nurse",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Biomedical Waste Audit",
                        "type": "Audit",
                        "start": 60,
                        "duration": 6,
                        "designation": "Staff Nurse",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Committee Formation",
                        "type": "Documentation",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Policy & SOP Drafting"],
                        "designation": "Hospital Administrator",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Staff Sensitisation",
                        "type": "Training",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Committee Formation"],
                        "designation": "Staff Nurse",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Assessment Visit",
                "designation": "Hospital Administrator",
                "tasks": [
                    {
                        "subject": "Internal Audit Round",
                        "type": "Audit",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Staff Sensitisation"],
                        "designation": "Pharmacist",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Mock Assessment",
                        "type": "Audit",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Staff Sensitisation"],
                        "designation": "Hospital Administrator",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Final Assessment Visit",
                        "type": "Audit",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Internal Audit Round", "Mock Assessment"],
                        "designation": "Hospital Administrator",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Diabetes Care Programme Launch",
        "project_type": "Clinical Programme",
        "priority": "Medium",
        "start_offset_days": -45,
        "notes": "A packaged diabetes care service with lab, pharmacy and counselling bundled.",
        "phases": [
            {
                "subject": "Design",
                "designation": "Hospital Administrator",
                "tasks": [
                    {
                        "subject": "Care Pathway Design",
                        "type": "Planning",
                        "start": 0,
                        "duration": 10,
                        "designation": "Hospital Administrator",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Package Costing",
                        "type": "Planning",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Care Pathway Design"],
                        "designation": "Billing Executive",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Medical Board Approval",
                        "type": "Documentation",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Package Costing"],
                        "designation": "Hospital Administrator",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Enablement",
                "designation": "Pharmacist",
                "tasks": [
                    {
                        "subject": "Lab Panel Setup",
                        "type": "Equipment",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Package Costing"],
                        "designation": "Lab Technician",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Pharmacy Formulary Update",
                        "type": "Documentation",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Package Costing"],
                        "designation": "Pharmacist",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Launch",
                "designation": "Hospital Administrator",
                "tasks": [
                    {
                        "subject": "Counsellor Training",
                        "type": "Training",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Medical Board Approval"],
                        "designation": "Staff Nurse",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Billing Package Configuration",
                        "type": "Documentation",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Counsellor Training", "Lab Panel Setup"],
                        "designation": "Billing Executive",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Programme Launch",
                        "type": "Launch",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Billing Package Configuration"],
                        "designation": "Hospital Administrator",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Day-Care Dialysis Unit Setup",
        "project_type": "Facility Setup",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Clinical Facility Commissioning",
        "notes": "Six-station dialysis unit, opened from the facility commissioning template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Healthcare Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
