"""Seeder: Projects and Tasks for Automobile.

Workshop expansion, a live recall campaign and a dealer systems rollout.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Service Campaign Playbook" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "Service Bay Expansion - Andheri Workshop",
        "project_type": "Workshop Setup",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "Four additional service bays and a dedicated alignment lane.",
        "phases": [
            {
                "subject": "Planning & Approvals",
                "designation": "Service Manager",
                "tasks": [
                    {
                        "subject": "Throughput Study",
                        "type": "Planning",
                        "start": 0,
                        "duration": 10,
                        "designation": "Service Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Bay Layout Drawings",
                        "type": "Planning",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Throughput Study"],
                        "designation": "Service Manager",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Fire & Municipal Approvals",
                        "type": "Planning",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Bay Layout Drawings"],
                        "designation": "Service Advisor",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Civil & Fit-out",
                "designation": "Service Manager",
                "tasks": [
                    {
                        "subject": "Civil Contractor Award",
                        "type": "Planning",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Fire & Municipal Approvals"],
                        "designation": "Parts Executive",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Lift Procurement",
                        "type": "Equipment",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Fire & Municipal Approvals"],
                        "designation": "Parts Executive",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Paint Booth Package",
                        "type": "Equipment",
                        "start": 70,
                        "duration": 20,
                        "designation": "Parts Executive",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Dropped after the group consolidated paint work at "
                        "the Thane site.",
                    },
                    {
                        "subject": "Diagnostic Tooling Order",
                        "type": "Equipment",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Civil Contractor Award"],
                        "designation": "Senior Mechanic",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Equipment & Training",
                "designation": "Senior Mechanic",
                "tasks": [
                    {
                        "subject": "Flooring & Drainage",
                        "type": "Civil Works",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Fire & Municipal Approvals"],
                        "designation": "Service Manager",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Site Safety Audit",
                        "type": "Inspection",
                        "start": 130,
                        "duration": 8,
                        "designation": "Service Advisor",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Bay Partition & Lighting",
                        "type": "Civil Works",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Flooring & Drainage", "Diagnostic Tooling Order"],
                        "designation": "Service Manager",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Signage Installation",
                        "type": "Civil Works",
                        "start": 150,
                        "duration": 10,
                        "designation": "Receptionist",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Lift Installation & Calibration",
                        "type": "Equipment",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Bay Partition & Lighting"],
                        "designation": "Senior Mechanic",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Launch",
                "designation": "Service Manager",
                "tasks": [
                    {
                        "subject": "Technician Training",
                        "type": "Training",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Lift Installation & Calibration"],
                        "designation": "Senior Mechanic",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Pre-opening Inspection",
                        "type": "Inspection",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Technician Training"],
                        "designation": "Service Advisor",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Bay Handover",
                        "type": "Rollout",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Pre-opening Inspection"],
                        "designation": "Service Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Recall Campaign - Model X Brake Actuator",
        "project_type": "Service Campaign",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "OEM-mandated brake actuator replacement across 1,240 affected vehicles.",
        "phases": [
            {
                "subject": "Campaign Setup",
                "designation": "Service Manager",
                "tasks": [
                    {
                        "subject": "Affected VIN Extraction",
                        "type": "Planning",
                        "start": 0,
                        "duration": 12,
                        "designation": "Service Advisor",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Actuator Stock Planning",
                        "type": "Planning",
                        "start": 5,
                        "duration": 10,
                        "designation": "Parts Executive",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Customer Outreach",
                "designation": "Service Advisor",
                "tasks": [
                    {
                        "subject": "Customer Notification Mailer",
                        "type": "Marketing",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Actuator Stock Planning", "Affected VIN Extraction"],
                        "designation": "Receptionist",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Loaner Vehicle Audit",
                        "type": "Inspection",
                        "start": 60,
                        "duration": 6,
                        "designation": "Service Advisor",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Outbound Call Drive",
                        "type": "Marketing",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Customer Notification Mailer"],
                        "designation": "Receptionist",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Appointment Scheduling",
                        "type": "Planning",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Outbound Call Drive"],
                        "designation": "Service Advisor",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Execution & Closure",
                "designation": "Senior Mechanic",
                "tasks": [
                    {
                        "subject": "Actuator Replacement Runs",
                        "type": "Inspection",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Appointment Scheduling"],
                        "designation": "Mechanic",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Post-repair Road Test",
                        "type": "Inspection",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Appointment Scheduling"],
                        "designation": "Senior Mechanic",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Campaign Closure Report",
                        "type": "Documentation",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Actuator Replacement Runs", "Post-repair Road Test"],
                        "designation": "Service Manager",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Dealer DMS Rollout",
        "project_type": "Dealer Program",
        "priority": "Medium",
        "start_offset_days": -45,
        "notes": "Replacing the legacy job-card system with the group DMS.",
        "phases": [
            {
                "subject": "Readiness",
                "designation": "Service Manager",
                "tasks": [
                    {
                        "subject": "Process Gap Analysis",
                        "type": "Planning",
                        "start": 0,
                        "duration": 10,
                        "designation": "Service Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Data Cleansing",
                        "type": "Documentation",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Process Gap Analysis"],
                        "designation": "Parts Executive",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Group IT Sign-off",
                        "type": "Planning",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Data Cleansing"],
                        "designation": "Service Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Migration",
                "designation": "Service Advisor",
                "tasks": [
                    {
                        "subject": "Master Data Migration",
                        "type": "Documentation",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Data Cleansing"],
                        "designation": "Parts Executive",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Job Card Template Setup",
                        "type": "Documentation",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Data Cleansing"],
                        "designation": "Service Advisor",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Go-Live",
                "designation": "Service Manager",
                "tasks": [
                    {
                        "subject": "Advisor Training",
                        "type": "Training",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Group IT Sign-off"],
                        "designation": "Service Advisor",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Parallel Run",
                        "type": "Rollout",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Advisor Training", "Master Data Migration"],
                        "designation": "Service Manager",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Cutover & Go-Live",
                        "type": "Rollout",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Parallel Run"],
                        "designation": "Service Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Annual Service Camp - Pune",
        "project_type": "Service Campaign",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Service Campaign Playbook",
        "notes": "Free multi-point check camp, generated from the campaign playbook.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Automobile Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
