"""Seeder: Projects and Tasks for Hobby & TCG.

A second store launch, a tournament series and a holiday season programme.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Store Launch Playbook" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "Second Store Launch - Riverside",
        "project_type": "Store Launch",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "A 2,400 sq ft store with a 12-table play space in the Riverside district.",
        "phases": [
            {
                "subject": "Planning",
                "designation": "Store Manager",
                "tasks": [
                    {
                        "subject": "Catchment Study",
                        "type": "Planning",
                        "start": 0,
                        "duration": 10,
                        "designation": "Store Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Lease Negotiation",
                        "type": "Planning",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Catchment Study"],
                        "designation": "Store Manager",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Permits & Signage Approval",
                        "type": "Planning",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Lease Negotiation"],
                        "designation": "Assistant Manager",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Build-out",
                "designation": "Assistant Manager",
                "tasks": [
                    {
                        "subject": "Store Layout Design",
                        "type": "Fit-out",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Permits & Signage Approval"],
                        "designation": "Assistant Manager",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Fixture & Shelving Order",
                        "type": "Fit-out",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Permits & Signage Approval"],
                        "designation": "Inventory Specialist",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "In-store Café Counter",
                        "type": "Fit-out",
                        "start": 70,
                        "duration": 20,
                        "designation": "Store Manager",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Dropped after the food handling permit timeline "
                        "blew past opening day.",
                    },
                    {
                        "subject": "Play Table Order",
                        "type": "Fit-out",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Store Layout Design"],
                        "designation": "Events Coordinator",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Stock & Staffing",
                "designation": "Inventory Specialist",
                "tasks": [
                    {
                        "subject": "Interior Build-out",
                        "type": "Fit-out",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Permits & Signage Approval"],
                        "designation": "Assistant Manager",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Fire Safety Inspection",
                        "type": "Planning",
                        "start": 130,
                        "duration": 8,
                        "designation": "Assistant Manager",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Play Space Build",
                        "type": "Fit-out",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Interior Build-out", "Play Table Order"],
                        "designation": "Events Coordinator",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Loyalty Programme Setup",
                        "type": "Marketing",
                        "start": 150,
                        "duration": 10,
                        "designation": "Sales Associate",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Opening Range Buy",
                        "type": "Inventory",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Play Space Build"],
                        "designation": "Inventory Specialist",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Opening",
                "designation": "Store Manager",
                "tasks": [
                    {
                        "subject": "Stock Receiving & Pricing",
                        "type": "Inventory",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Opening Range Buy"],
                        "designation": "Inventory Specialist",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Staff Hiring & Training",
                        "type": "Staffing",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Stock Receiving & Pricing"],
                        "designation": "Assistant Manager",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Opening Day",
                        "type": "Launch",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Staff Hiring & Training"],
                        "designation": "Store Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Regional Tournament Series - Spring Circuit",
        "project_type": "Event Series",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "Eight weekly qualifiers feeding a regional final, with vendor prize support.",
        "phases": [
            {
                "subject": "Calendar & Support",
                "designation": "Events Coordinator",
                "tasks": [
                    {
                        "subject": "Season Calendar",
                        "type": "Planning",
                        "start": 0,
                        "duration": 12,
                        "designation": "Events Coordinator",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Prize Support Request",
                        "type": "Planning",
                        "start": 5,
                        "duration": 10,
                        "designation": "Store Manager",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Promotion & Run",
                "designation": "Events Coordinator",
                "tasks": [
                    {
                        "subject": "Event Listing & Signup",
                        "type": "Marketing",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Prize Support Request", "Season Calendar"],
                        "designation": "Sales Associate",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Venue Safety Check",
                        "type": "Planning",
                        "start": 60,
                        "duration": 6,
                        "designation": "Assistant Manager",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Judge Roster",
                        "type": "Staffing",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Event Listing & Signup"],
                        "designation": "Events Coordinator",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Weekly Qualifier Rounds",
                        "type": "Event Ops",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Judge Roster"],
                        "designation": "Events Coordinator",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Wrap-up",
                "designation": "Store Manager",
                "tasks": [
                    {
                        "subject": "Regional Final",
                        "type": "Event Ops",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Weekly Qualifier Rounds"],
                        "designation": "Events Coordinator",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Prize Distribution",
                        "type": "Event Ops",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Weekly Qualifier Rounds"],
                        "designation": "Inventory Specialist",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Season Report",
                        "type": "Planning",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Regional Final", "Prize Distribution"],
                        "designation": "Store Manager",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Holiday Season Programme",
        "project_type": "Season Programme",
        "priority": "High",
        "start_offset_days": -45,
        "notes": "Buying, bundling and staffing plan for the November-December peak.",
        "phases": [
            {
                "subject": "Planning",
                "designation": "Store Manager",
                "tasks": [
                    {
                        "subject": "Prior Season Analysis",
                        "type": "Planning",
                        "start": 0,
                        "duration": 10,
                        "designation": "Store Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Range & Bundle Plan",
                        "type": "Planning",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Prior Season Analysis"],
                        "designation": "Inventory Specialist",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Budget Sign-off",
                        "type": "Planning",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Range & Bundle Plan"],
                        "designation": "Store Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Buying",
                "designation": "Inventory Specialist",
                "tasks": [
                    {
                        "subject": "Vendor Pre-orders",
                        "type": "Inventory",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Range & Bundle Plan"],
                        "designation": "Inventory Specialist",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Gift Bundle Assembly",
                        "type": "Merchandising",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Range & Bundle Plan"],
                        "designation": "Sales Associate",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Execution",
                "designation": "Store Manager",
                "tasks": [
                    {
                        "subject": "Seasonal Staff Hiring",
                        "type": "Staffing",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Budget Sign-off"],
                        "designation": "Assistant Manager",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Window & Display Refresh",
                        "type": "Merchandising",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Seasonal Staff Hiring", "Vendor Pre-orders"],
                        "designation": "Sales Associate",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Holiday Campaign Launch",
                        "type": "Marketing",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Window & Display Refresh"],
                        "designation": "Store Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Pop-up Booth - Comic Expo",
        "project_type": "Store Launch",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Store Launch Playbook",
        "notes": "Convention pop-up, opened from the store launch playbook.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Hobby & TCG Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
