"""Seeder: Projects and Tasks for 3D Printing.

An aerospace prototype programme, a dental batch run and a capacity expansion.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Prototype Delivery Programme" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "Aerospace Bracket Prototype Programme",
        "project_type": "Prototype Programme",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "Three iterations of a topology-optimised titanium bracket for a Tier-1 supplier.",
        "phases": [
            {
                "subject": "Definition",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Client Requirement Capture",
                        "type": "Requirements",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Material Selection",
                        "type": "Requirements",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Client Requirement Capture"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Design for Additive Review",
                        "type": "CAD Prep",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Material Selection"],
                        "designation": "Print Floor Supervisor",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Preparation",
                "designation": "Print Floor Supervisor",
                "tasks": [
                    {
                        "subject": "File Repair & Orientation",
                        "type": "CAD Prep",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Design for Additive Review"],
                        "designation": "SLA Print Technician",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Support Strategy",
                        "type": "CAD Prep",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Design for Additive Review"],
                        "designation": "SLA Print Technician",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Metal Powder Qualification",
                        "type": "Requirements",
                        "start": 70,
                        "duration": 20,
                        "designation": "Production Manager",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Paused — the client moved the first articles to a "
                        "polymer surrogate.",
                    },
                    {
                        "subject": "Material Procurement",
                        "type": "Printing",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["File Repair & Orientation"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Build & Iterate",
                "designation": "Print Floor Supervisor",
                "tasks": [
                    {
                        "subject": "First Article Print",
                        "type": "Printing",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Design for Additive Review"],
                        "designation": "FDM Print Technician",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Resin Handling Safety Audit",
                        "type": "Inspection",
                        "start": 130,
                        "duration": 8,
                        "designation": "QC Inspector",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Dimensional Inspection",
                        "type": "Inspection",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["First Article Print", "Material Procurement"],
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Fixture Design for Finishing",
                        "type": "CAD Prep",
                        "start": 150,
                        "duration": 10,
                        "designation": "Finishing Technician",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Iteration Print Run",
                        "type": "Printing",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Dimensional Inspection"],
                        "designation": "SLA Print Technician",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Delivery",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Post-Processing & Curing",
                        "type": "Post-Processing",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Iteration Print Run"],
                        "designation": "Post-Processing Technician",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Finishing & Assembly",
                        "type": "Finishing",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Post-Processing & Curing"],
                        "designation": "Finishing Technician",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Client Delivery",
                        "type": "Shipping",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Finishing & Assembly"],
                        "designation": "Shipping Associate",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Dental Aligner Batch Run - Q3",
        "project_type": "Client Print Job",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "A 4,200-model quarterly run for a dental aligner customer.",
        "phases": [
            {
                "subject": "Order Setup",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Order Review",
                        "type": "Requirements",
                        "start": 0,
                        "duration": 12,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Quote Confirmation",
                        "type": "Requirements",
                        "start": 5,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Production",
                "designation": "Print Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Build Plate Nesting",
                        "type": "CAD Prep",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Quote Confirmation", "Order Review"],
                        "designation": "SLA Print Technician",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Biocompatibility Check",
                        "type": "Inspection",
                        "start": 60,
                        "duration": 6,
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Machine Scheduling",
                        "type": "Printing",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Build Plate Nesting"],
                        "designation": "Print Floor Supervisor",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Batch Printing",
                        "type": "Printing",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Machine Scheduling"],
                        "designation": "SLA Print Technician",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Despatch",
                "designation": "Shipping Associate",
                "tasks": [
                    {
                        "subject": "Support Removal & Curing",
                        "type": "Post-Processing",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Batch Printing"],
                        "designation": "Post-Processing Technician",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Final Inspection",
                        "type": "Inspection",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Batch Printing"],
                        "designation": "QC Inspector",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Packing & Despatch",
                        "type": "Shipping",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Support Removal & Curing", "Final Inspection"],
                        "designation": "Shipping Associate",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "SLS Cell Installation",
        "project_type": "Capacity Expansion",
        "priority": "High",
        "start_offset_days": -45,
        "notes": "Adding a selective laser sintering cell with powder handling and depowdering.",
        "phases": [
            {
                "subject": "Planning",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Capacity Business Case",
                        "type": "Requirements",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Vendor Evaluation",
                        "type": "Requirements",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Capacity Business Case"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Capital Approval",
                        "type": "Requirements",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Vendor Evaluation"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Site Preparation",
                "designation": "Print Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Room Preparation",
                        "type": "Installation",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Vendor Evaluation"],
                        "designation": "Finishing Technician",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Power & Extraction Hook-up",
                        "type": "Installation",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Vendor Evaluation"],
                        "designation": "Post-Processing Technician",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Commissioning",
                "designation": "Print Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Machine Installation",
                        "type": "Installation",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Capital Approval"],
                        "designation": "Print Floor Supervisor",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Operator Training",
                        "type": "Installation",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Machine Installation", "Room Preparation"],
                        "designation": "FDM Print Technician",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Acceptance Print Run",
                        "type": "Printing",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Operator Training"],
                        "designation": "Print Floor Supervisor",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Automotive Jig Prototype Run",
        "project_type": "Prototype Programme",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Prototype Delivery Programme",
        "notes": "Assembly jig prototypes, opened from the prototype delivery template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "3D Printing Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
