"""Seeder: Projects and Tasks for Garment.

A seasonal collection, an export buyer ramp-up and a compliance audit.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Seasonal Collection Development" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "AW26 Collection Development",
        "project_type": "Seasonal Collection",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "Autumn/Winter 2026 womenswear line — 42 styles across four stories.",
        "phases": [
            {
                "subject": "Design",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Trend Research",
                        "type": "Design",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Line Sheet Freeze",
                        "type": "Design",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Trend Research"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Tech Pack Release",
                        "type": "Design",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Line Sheet Freeze"],
                        "designation": "Cutting Master",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Sourcing & Sampling",
                "designation": "Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Fabric Sourcing",
                        "type": "Sourcing",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Tech Pack Release"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Trim & Button Sourcing",
                        "type": "Sourcing",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Tech Pack Release"],
                        "designation": "Button Machine Operator",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Hand-embroidered Story",
                        "type": "Design",
                        "start": 70,
                        "duration": 20,
                        "designation": "Floor Supervisor",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Cut from the season after the karigar capacity was "
                        "booked out.",
                    },
                    {
                        "subject": "Proto Sample Round",
                        "type": "Sampling",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Fabric Sourcing"],
                        "designation": "Sewing Operator",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Bulk Production",
                "designation": "Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Fit Sample Approval",
                        "type": "Sampling",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Tech Pack Release"],
                        "designation": "QC Checker",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Line Safety Audit",
                        "type": "Inspection",
                        "start": 130,
                        "duration": 8,
                        "designation": "QC Checker",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Bulk Fabric Inspection",
                        "type": "Inspection",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Fit Sample Approval", "Proto Sample Round"],
                        "designation": "QC Checker",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Care Label Artwork",
                        "type": "Finishing",
                        "start": 150,
                        "duration": 10,
                        "designation": "Packaging Operator",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Marker & Bulk Cutting",
                        "type": "Cutting",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Bulk Fabric Inspection"],
                        "designation": "Cutting Master",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Despatch",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Line Loading & Sewing",
                        "type": "Stitching",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Marker & Bulk Cutting"],
                        "designation": "Sewing Operator",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Pressing & Packing",
                        "type": "Finishing",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Line Loading & Sewing"],
                        "designation": "Pressing Operator",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Collection Despatch",
                        "type": "Shipping",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Pressing & Packing"],
                        "designation": "Packaging Operator",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Export Buyer Order Ramp - Nordwear",
        "project_type": "Buyer Programme",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "First 38,000-piece order for a Scandinavian buyer, ramping two new lines.",
        "phases": [
            {
                "subject": "Order Setup",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Order Confirmation",
                        "type": "Design",
                        "start": 0,
                        "duration": 12,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Costing Sign-off",
                        "type": "Design",
                        "start": 5,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Sampling & Bulk",
                "designation": "Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Fabric Booking",
                        "type": "Sourcing",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Costing Sign-off", "Order Confirmation"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Social Compliance Audit",
                        "type": "Inspection",
                        "start": 60,
                        "duration": 6,
                        "designation": "QC Checker",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Pre-production Sample",
                        "type": "Sampling",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Fabric Booking"],
                        "designation": "Sewing Operator",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Cutting & Bundling",
                        "type": "Cutting",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Pre-production Sample"],
                        "designation": "Cutting Master",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Shipment",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Sewing & Overlock Runs",
                        "type": "Stitching",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Cutting & Bundling"],
                        "designation": "Overlock Operator",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Buyer Final Audit",
                        "type": "Inspection",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Cutting & Bundling"],
                        "designation": "QC Checker",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Shipment Documentation",
                        "type": "Shipping",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Sewing & Overlock Runs", "Buyer Final Audit"],
                        "designation": "Packaging Operator",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "SEDEX Compliance Audit",
        "project_type": "Compliance Audit",
        "priority": "High",
        "start_offset_days": -45,
        "notes": "SMETA 4-pillar audit ahead of the European buyer onboarding.",
        "phases": [
            {
                "subject": "Preparation",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Self Assessment Questionnaire",
                        "type": "Inspection",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Gap Analysis",
                        "type": "Inspection",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Self Assessment Questionnaire"],
                        "designation": "QC Checker",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Management Sign-off",
                        "type": "Inspection",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Gap Analysis"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Remediation",
                "designation": "Floor Supervisor",
                "tasks": [
                    {
                        "subject": "Records & Register Update",
                        "type": "Inspection",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Gap Analysis"],
                        "designation": "Floor Supervisor",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Worker Awareness Sessions",
                        "type": "Inspection",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Gap Analysis"],
                        "designation": "Floor Supervisor",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Audit",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Fire & Electrical Remediation",
                        "type": "Finishing",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Management Sign-off"],
                        "designation": "Floor Supervisor",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Pre-audit Walkthrough",
                        "type": "Inspection",
                        "start": 78,
                        "duration": 22,
                        "depends_on": [
                            "Fire & Electrical Remediation",
                            "Records & Register Update",
                        ],
                        "designation": "QC Checker",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "SMETA Audit Day",
                        "type": "Inspection",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Pre-audit Walkthrough"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "SS27 Capsule Line",
        "project_type": "Seasonal Collection",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Seasonal Collection Development",
        "notes": "Spring/Summer capsule, opened from the seasonal collection template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Garment Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
