"""Seeder: Projects and Tasks for EV Manufacturing.

A powertrain development programme, a battery line commissioning and a homologation.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "EV Product Development" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "2W Powertrain NPD - Volt 3.5kW",
        "project_type": "New Product Development",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "A 3.5 kW hub-motor powertrain with an integrated 48V pack for the city commuter "
        "range.",
        "phases": [
            {
                "subject": "Concept & Design",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Requirement Definition",
                        "type": "Design",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Powertrain Sizing",
                        "type": "Design",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Requirement Definition"],
                        "designation": "Motor Assembly Technician",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "Pack Architecture",
                        "type": "Design",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Powertrain Sizing"],
                        "designation": "Pack Integration Engineer",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Tooling & Sourcing",
                "designation": "Line Supervisor",
                "tasks": [
                    {
                        "subject": "Motor Supplier Selection",
                        "type": "Tooling",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["Pack Architecture"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Cell Supplier Qualification",
                        "type": "Tooling",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["Pack Architecture"],
                        "designation": "Battery Assembly Technician",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Liquid-Cooled Pack Variant",
                        "type": "Design",
                        "start": 70,
                        "duration": 20,
                        "designation": "Pack Integration Engineer",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Shelved — air cooling met the thermal target at the "
                        "target price point.",
                    },
                    {
                        "subject": "Prototype Tooling",
                        "type": "Tooling",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Motor Supplier Selection"],
                        "designation": "Chassis Welder",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Prototype & Validate",
                "designation": "PDI Test Engineer",
                "tasks": [
                    {
                        "subject": "Mule Vehicle Build",
                        "type": "Prototyping",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["Pack Architecture"],
                        "designation": "Body Fitment Technician",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "High Voltage Safety Audit",
                        "type": "Validation",
                        "start": 130,
                        "duration": 8,
                        "designation": "QC Inspector",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Bench Validation",
                        "type": "Validation",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Mule Vehicle Build", "Prototype Tooling"],
                        "designation": "PDI Test Engineer",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Wiring Harness Routing",
                        "type": "Assembly",
                        "start": 150,
                        "duration": 10,
                        "designation": "EV Electrical Technician",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Durability Testing",
                        "type": "Validation",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Bench Validation"],
                        "designation": "PDI Test Engineer",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Release",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Thermal Soak Testing",
                        "type": "Validation",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Durability Testing"],
                        "designation": "PDI Test Engineer",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "Design Freeze Review",
                        "type": "Design",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Thermal Soak Testing"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Production Release",
                        "type": "Documentation",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["Design Freeze Review"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Battery Pack Line Commissioning",
        "project_type": "Line Commissioning",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "New 120 packs/shift module and pack assembly line in Bay 3.",
        "phases": [
            {
                "subject": "Planning",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Line Layout Design",
                        "type": "Design",
                        "start": 0,
                        "duration": 12,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Cycle Time Study",
                        "type": "Design",
                        "start": 5,
                        "duration": 10,
                        "designation": "Line Supervisor",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Installation",
                "designation": "Line Supervisor",
                "tasks": [
                    {
                        "subject": "Equipment Installation",
                        "type": "Assembly",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Cycle Time Study", "Line Layout Design"],
                        "designation": "Line Supervisor",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Electrical Safety Audit",
                        "type": "Validation",
                        "start": 60,
                        "duration": 6,
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Utility & Busbar Hook-up",
                        "type": "Assembly",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["Equipment Installation"],
                        "designation": "EV Electrical Technician",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Fixture Commissioning",
                        "type": "Tooling",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Utility & Busbar Hook-up"],
                        "designation": "Battery Assembly Technician",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Trial & Ramp-up",
                "designation": "Line Supervisor",
                "tasks": [
                    {
                        "subject": "Dry Run",
                        "type": "Validation",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Fixture Commissioning"],
                        "designation": "Line Supervisor",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Operator Training",
                        "type": "Training",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Fixture Commissioning"],
                        "designation": "Line Supervisor",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Trial Production Batch",
                        "type": "Validation",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Dry Run", "Operator Training"],
                        "designation": "Battery Assembly Technician",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "ARAI Homologation - Voltara City",
        "project_type": "Homologation",
        "priority": "High",
        "start_offset_days": -45,
        "notes": "CMVR homologation of the Voltara City variant at ARAI Pune.",
        "phases": [
            {
                "subject": "Dossier",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Regulation Applicability Study",
                        "type": "Homologation",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Technical Dossier Preparation",
                        "type": "Homologation",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Regulation Applicability Study"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "ARAI Slot Confirmation",
                        "type": "Homologation",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Technical Dossier Preparation"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Sample Preparation",
                "designation": "Line Supervisor",
                "tasks": [
                    {
                        "subject": "Test Sample Build",
                        "type": "Assembly",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Technical Dossier Preparation"],
                        "designation": "Body Fitment Technician",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Instrumentation Fitment",
                        "type": "Assembly",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Technical Dossier Preparation"],
                        "designation": "EV Electrical Technician",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Test Campaign",
                "designation": "PDI Test Engineer",
                "tasks": [
                    {
                        "subject": "Safety & EMC Testing",
                        "type": "Homologation",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["ARAI Slot Confirmation"],
                        "designation": "PDI Test Engineer",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Range & Performance Testing",
                        "type": "Homologation",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Safety & EMC Testing", "Test Sample Build"],
                        "designation": "PDI Test Engineer",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Type Approval Issue",
                        "type": "Documentation",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Range & Performance Testing"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Fleet Variant NPD - Cargo 2W",
        "project_type": "New Product Development",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "EV Product Development",
        "notes": "Cargo variant, started from the standard product development template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "EV Manufacturing Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
