"""Seeder: Projects and Tasks for Jewellery.

A bridal collection launch, a bespoke commission and an exhibition programme.

Each project sits at a different stage of its life, and the last one is generated
by ERPNext itself from the "Collection Development" Project Template — so the Gantt chart,
the Kanban board and the template flow all have something to show.
"""

from __future__ import annotations

from demostackkit.seeder.project_seeders import ProjectSeeder as _ProjectSeederBase

PROJECT_BLUEPRINTS = [
    {
        "name": "Bridal Collection Launch - Vivaha",
        "project_type": "Collection Launch",
        "priority": "High",
        "start_offset_days": -150,
        "notes": "A 24-piece polki and uncut diamond bridal collection for the wedding season.",
        "phases": [
            {
                "subject": "Concept & Design",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Theme Research",
                        "type": "Design",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 60,
                    },
                    {
                        "subject": "Design Sketches",
                        "type": "Design",
                        "start": 10,
                        "duration": 20,
                        "depends_on": ["Theme Research"],
                        "designation": "Filing & Shaping Artisan",
                        "priority": "High",
                        "hours": 120,
                    },
                    {
                        "subject": "CAD Modelling & Approval",
                        "type": "Design",
                        "start": 30,
                        "duration": 25,
                        "depends_on": ["Design Sketches"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 80,
                    },
                ],
            },
            {
                "subject": "Sourcing & Prototyping",
                "designation": "Karigar Supervisor",
                "tasks": [
                    {
                        "subject": "Polki Stone Sourcing",
                        "type": "Setting",
                        "start": 55,
                        "duration": 20,
                        "depends_on": ["CAD Modelling & Approval"],
                        "designation": "Stone Setter",
                        "priority": "High",
                        "hours": 40,
                    },
                    {
                        "subject": "Bullion Allocation",
                        "type": "Casting",
                        "start": 60,
                        "duration": 25,
                        "depends_on": ["CAD Modelling & Approval"],
                        "designation": "Melting Furnace Operator",
                        "priority": "Medium",
                        "hours": 40,
                    },
                    {
                        "subject": "Enamel Meenakari Range",
                        "type": "Design",
                        "start": 70,
                        "duration": 20,
                        "designation": "Production Manager",
                        "priority": "Low",
                        "hours": 24,
                        "status": "Cancelled",
                        "description": "Held over to the next collection — the meenakari "
                        "workshop is at capacity.",
                    },
                    {
                        "subject": "Master Wax Carving",
                        "type": "Casting",
                        "start": 80,
                        "duration": 30,
                        "depends_on": ["Polki Stone Sourcing"],
                        "designation": "Casting Technician",
                        "priority": "Medium",
                        "hours": 56,
                    },
                ],
            },
            {
                "subject": "Production",
                "designation": "Karigar Supervisor",
                "tasks": [
                    {
                        "subject": "Prototype Casting",
                        "type": "Casting",
                        "start": 95,
                        "duration": 30,
                        "depends_on": ["CAD Modelling & Approval"],
                        "designation": "Casting Technician",
                        "priority": "High",
                        "hours": 200,
                    },
                    {
                        "subject": "Strongroom Stock Audit",
                        "type": "Inspection",
                        "start": 130,
                        "duration": 8,
                        "designation": "QC Inspector",
                        "priority": "Urgent",
                        "hours": 16,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Bulk Casting Run",
                        "type": "Casting",
                        "start": 125,
                        "duration": 25,
                        "depends_on": ["Prototype Casting", "Master Wax Carving"],
                        "designation": "Casting Technician",
                        "priority": "High",
                        "hours": 240,
                        "status": "Pending Review",
                    },
                    {
                        "subject": "Catalogue Photography",
                        "type": "Merchandising",
                        "start": 150,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "Low",
                        "hours": 32,
                        "status": "Open",
                    },
                    {
                        "subject": "Stone Setting",
                        "type": "Setting",
                        "start": 145,
                        "duration": 25,
                        "depends_on": ["Bulk Casting Run"],
                        "designation": "Stone Setter",
                        "priority": "High",
                        "hours": 160,
                    },
                ],
            },
            {
                "subject": "Launch",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Polishing & Rhodium Plating",
                        "type": "Finishing",
                        "start": 170,
                        "duration": 15,
                        "depends_on": ["Stone Setting"],
                        "designation": "Polishing Artisan",
                        "priority": "High",
                        "hours": 80,
                    },
                    {
                        "subject": "BIS Hallmarking",
                        "type": "Hallmarking",
                        "start": 185,
                        "duration": 12,
                        "depends_on": ["Polishing & Rhodium Plating"],
                        "designation": "Hallmarking Technician",
                        "priority": "Urgent",
                        "hours": 64,
                    },
                    {
                        "subject": "Counter Launch",
                        "type": "Merchandising",
                        "start": 197,
                        "duration": 5,
                        "depends_on": ["BIS Hallmarking"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 16,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Bespoke Commission - Mehta Necklace Set",
        "project_type": "Bespoke Commission",
        "priority": "High",
        "start_offset_days": -95,
        "notes": "A commissioned emerald and diamond necklace set with matching earrings.",
        "phases": [
            {
                "subject": "Brief & Design",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Client Brief",
                        "type": "Design",
                        "start": 0,
                        "duration": 12,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 72,
                    },
                    {
                        "subject": "Budget & Estimate",
                        "type": "Design",
                        "start": 5,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 40,
                    },
                ],
            },
            {
                "subject": "Make",
                "designation": "Karigar Supervisor",
                "tasks": [
                    {
                        "subject": "CAD Rendering & Approval",
                        "type": "Design",
                        "start": 15,
                        "duration": 30,
                        "depends_on": ["Budget & Estimate", "Client Brief"],
                        "designation": "Filing & Shaping Artisan",
                        "priority": "High",
                        "hours": 220,
                    },
                    {
                        "subject": "Stone Authenticity Check",
                        "type": "Inspection",
                        "start": 60,
                        "duration": 6,
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 12,
                        "status": "Overdue",
                    },
                    {
                        "subject": "Emerald Selection",
                        "type": "Setting",
                        "start": 45,
                        "duration": 28,
                        "depends_on": ["CAD Rendering & Approval"],
                        "designation": "Stone Setter",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Casting & Assembly",
                        "type": "Casting",
                        "start": 73,
                        "duration": 22,
                        "depends_on": ["Emerald Selection"],
                        "designation": "Casting Technician",
                        "priority": "Medium",
                        "hours": 140,
                    },
                ],
            },
            {
                "subject": "Delivery",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Setting & Finishing",
                        "type": "Finishing",
                        "start": 95,
                        "duration": 25,
                        "depends_on": ["Casting & Assembly"],
                        "designation": "Polishing Artisan",
                        "priority": "Medium",
                        "hours": 120,
                        "status": "Open",
                    },
                    {
                        "subject": "Hallmark & Certification",
                        "type": "Hallmarking",
                        "start": 110,
                        "duration": 15,
                        "depends_on": ["Casting & Assembly"],
                        "designation": "Hallmarking Technician",
                        "priority": "Medium",
                        "hours": 64,
                    },
                    {
                        "subject": "Client Delivery",
                        "type": "Logistics",
                        "start": 125,
                        "duration": 10,
                        "depends_on": ["Setting & Finishing", "Hallmark & Certification"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 24,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "India Jewellery Show - Mumbai",
        "project_type": "Exhibition",
        "priority": "Medium",
        "start_offset_days": -45,
        "notes": "Participation at the Mumbai edition with a 36 sq m stall.",
        "phases": [
            {
                "subject": "Planning",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Stall Booking",
                        "type": "Merchandising",
                        "start": 0,
                        "duration": 10,
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 48,
                    },
                    {
                        "subject": "Stall Design",
                        "type": "Merchandising",
                        "start": 10,
                        "duration": 18,
                        "depends_on": ["Stall Booking"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 96,
                    },
                    {
                        "subject": "Budget Approval",
                        "type": "Merchandising",
                        "start": 28,
                        "duration": 20,
                        "depends_on": ["Stall Design"],
                        "designation": "Production Manager",
                        "priority": "Urgent",
                        "hours": 40,
                        "status": "Pending Review",
                    },
                ],
            },
            {
                "subject": "Preparation",
                "designation": "Karigar Supervisor",
                "tasks": [
                    {
                        "subject": "Display Piece Selection",
                        "type": "Merchandising",
                        "start": 30,
                        "duration": 15,
                        "depends_on": ["Stall Design"],
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 32,
                    },
                    {
                        "subject": "Insurance & Transit Cover",
                        "type": "Logistics",
                        "start": 40,
                        "duration": 18,
                        "depends_on": ["Stall Design"],
                        "designation": "Production Manager",
                        "priority": "Medium",
                        "hours": 28,
                        "status": "Open",
                    },
                ],
            },
            {
                "subject": "Show",
                "designation": "Production Manager",
                "tasks": [
                    {
                        "subject": "Stall Fabrication",
                        "type": "Merchandising",
                        "start": 48,
                        "duration": 30,
                        "depends_on": ["Budget Approval"],
                        "designation": "Filing & Shaping Artisan",
                        "priority": "High",
                        "hours": 180,
                    },
                    {
                        "subject": "Secure Transport",
                        "type": "Logistics",
                        "start": 78,
                        "duration": 22,
                        "depends_on": ["Stall Fabrication", "Display Piece Selection"],
                        "designation": "QC Inspector",
                        "priority": "High",
                        "hours": 140,
                    },
                    {
                        "subject": "Show Days & Order Book",
                        "type": "Merchandising",
                        "start": 100,
                        "duration": 12,
                        "depends_on": ["Secure Transport"],
                        "designation": "Production Manager",
                        "priority": "High",
                        "hours": 40,
                        "milestone": True,
                    },
                ],
            },
        ],
    },
    {
        "name": "Festive Collection - Deepavali",
        "project_type": "Collection Launch",
        "priority": "Medium",
        "start_offset_days": -25,
        "duration": 120,
        "template": "Collection Development",
        "notes": "Lightweight festive range, opened from the collection development template.",
    },
]


class ProjectSeeder(_ProjectSeederBase):
    label = "Jewellery Projects & Tasks"
    PROJECT_BLUEPRINTS = PROJECT_BLUEPRINTS
